#pragma once

#include "lvgl.h"

// Noto Sans TC (Traditional Chinese) bitmap fonts generated by lv_font_conv.
// These fonts contain ~3500 common Traditional Chinese characters + ASCII + punctuation.
// They are designed to be used as fallback fonts for LVGL's built-in Montserrat.

LV_FONT_DECLARE(font_noto_tc_20);
LV_FONT_DECLARE(font_noto_tc_24);
